# Generated by Django 5.2.8 on 2026-06-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElqaUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elqa', models.CharField(choices=[('sindhakhall', 'Sindhakhall'), ('talash', 'Talash'), ('collage', 'Collage'), ('shaher', 'Shaher'), ('bazam', 'Bazam'), ('colleges', 'Colleges')], max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Halqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elqa', models.CharField(choices=[('sindhakhall', 'Sindhakhall'), ('talash', 'Talash'), ('collage', 'Collage'), ('shaher', 'Shaher'), ('bazam', 'Bazam'), ('colleges', 'Colleges')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elqa', models.CharField(choices=[('sindhakhall', 'Sindhakhall'), ('talash', 'Talash'), ('collage', 'Collage'), ('shaher', 'Shaher'), ('bazam', 'Bazam'), ('colleges', 'Colleges')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
