# Generated by Django 5.2.8 on 2026-06-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='halqa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.halqa'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('karkun', 'کارکن'), ('rafiq', 'رفیق'), ('umeedwar', 'امیدوار')], default='karkun', max_length=20),
        ),
    ]
